# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Vendors'
  link: '/vendors'
- label: 'Cisco'
  items:
    - label: 'Nexus'
      link: '/cisco/nexus'
    - label: 'ASA'
      link: '/cisco/asa'
    - label: 'ASR'
      link: '/cisco/asr'
- label: 'Palo Alto'
  items:
    - label: 'Panorama'
      link: '/palo-alto/panorama'
- label: 'F5 Big-IP'
  items:
    - label: 'LTM'
      link: '/f5/ltm'
    - label: 'DNS'
      link: '/f5/dns'
